### PR TITLE
allowed for variable quantity in orders

### LINKED ISSUE #7: Allow specific quantities of an item to be ordered.
Currently, ordering an item orders its entire quantity. So if we have 10 cans of corn, and we only want maybe 2 cans to go to any one student, we would enter in 5 different items and just specify a quantity of 2 each.

We need functionality to allow users to select a quantity lesser than or equal to the maximum for that item. When an order is placed, we need to then update the row to reduce the quantity accordingly.

### PR DESCRIPTION
**Pull request by mcole24**
quantity column will need to be added to the order_items table when this change is deployed to the production site.

Bug exists when changing quantity more than once but this is tolerable for now. Will fix later.

### CODE REVIEW

**Comment by JackFly26** [comment]
I ran it on my end, and the "Order" button isn't showing up.

**Comment by JackFly26** [comment]
Nevermind, I forgot I reloaded the sql file.

**Comment by polyrtm** [comment]
When I order an item and then order the same quantity, it says to select at least one item, even though I already have.

**Comment by mcole24** [comment]
@JackFly26 , that's a good catch. I didn't test it enough. I made some changes. There is still a bug pertaining to the quantities displayed in the confirmation modal if you exit out of the modal and then change the quantity. The modal doesn't reflect the new quantity. But that can be fixed in a later issue. I went ahead and removed the quantity display from the modal for now. Everything else should work though.

**Pull request merged**
